sudo:required
services:
    - docker

before_install:
    - docker build -t chetanpotdar25/bank-repo -f Dockerfile . 
script:
    - docker run  chetanpotdar25/bank-repo npm run test -- -- coverage   
    
